#!/usr/local/CyberCP/bin/python

import os.path
import sys
import django
sys.path.append('/usr/local/CyberCP')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "CyberCP.settings")
django.setup()
from loginSystem.models import Administrator, ACL
from plogical import hashPassword
from plogical.acl import ACLManager
from packages.models import Package
from baseTemplate.models import version

VERSION = '2.3'
BUILD = 9

def main():
    adminUser = 'cyberpanel'
    adminEmail = 'cyberpanel@example.ltd'
    adminPass = 'MkrCP@334'

    numberOfAdministrator = Administrator.objects.count()
    print('[*] Administrator count: %s' % str(numberOfAdministrator))

    token = hashPassword.generateToken('admin', adminPass)
    try:
        currentAdmin = Administrator.objects.get(userName=adminUser)
        currentAdmin.password = hashPassword.hash_password(adminPass)
        currentAdmin.token = token
        currentAdmin.save()
    except Exception as e:
        print(e)

        ACLManager.createDefaultACLs()
        acl = ACL.objects.get(name='admin')
        
        admin = Administrator(userName=adminUser, password=hashPassword.hash_password(adminPass), type=1, email=adminEmail, firstName="Cyber", lastName="Panel", acl=acl, token=token)
        admin.save()
        
        vers = version(currentVersion=VERSION, build=BUILD)
        vers.save()
        
        package = Package(admin=admin, packageName="CyberPanel", diskSpace=1000,
                        bandwidth=1000, ftpAccounts=1000, dataBases=1000,
                        emailAccounts=1000, allowedDomains=20)
        package.save()

    print("[+] Admin password successfully changed!")
    print("[+] Username: %s" % adminUser)
    print("[+] Password: %s" % adminPass)


if __name__ == "__main__":
    main()
